version: '3'

services:
    nexus3:
        container_name: nexus3
        image: sonatype/nexus3
        restart: always
        ports:
            - 18081:8081
            - 15000:5000
        volumes:
            - ./nexus-data:/nexus-data
        user: root
